"""Create the links table.

Revision ID: a58b4273396c
Revises:
Create Date: 2026-08-17 04:08:57.960493

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a58b4273396c'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Create the links table and its lookup indexes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'links',
        sa.Column('subpart', sa.String(length=32), nullable=False),
        sa.Column('url', sa.String(length=2048), nullable=False),
        sa.Column('owner_session_id', sa.String(length=36), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('clicks', sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint('subpart'),
    )
    op.create_index(op.f('ix_links_created_at'), 'links', ['created_at'], unique=False)
    op.create_index(
        op.f('ix_links_owner_session_id'),
        'links',
        ['owner_session_id'],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Drop the links table and its lookup indexes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_links_owner_session_id'), table_name='links')
    op.drop_index(op.f('ix_links_created_at'), table_name='links')
    op.drop_table('links')
    # ### end Alembic commands ###
